name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Setup pages
      id: pages
      uses: actions/configure-pages@v1
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: make
    - name: Prepare artifact
      run: |
        mkdir -p _site
        mv output/wigator.html _site/index.html
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      id: deployment
      uses: actions/deploy-pages@v1
