name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: make

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Configure pages
      uses: actions/configure-pages@v1
    - name: Prepare
      run: |
        mkdir -p _site
        mv output/wigator.html _site/index.html
    - name: Upload
      uses: actions/upload-pages-artifact@v1
    - name: Deploy
      uses: actions/deploy-pages@v1
